In [8]:
arr1=np.array([[1,2,3],[4,5,6]])

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr1*arr1

array([[ 1,  4,  9],
       [16, 25, 36]])

In [11]:
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
arr1/arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr1**arr1

array([[    1,     4,    27],
       [  256,  3125, 46656]], dtype=int32)

In [17]:
arr1**5

array([[   1,   32,  243],
       [1024, 3125, 7776]], dtype=int32)